INSERT INTO `ak_items`(title,category,keywords)VALUES('定下“硬杠杠”饼干新国标出台','1','饼干,定下,杠杠');
INSERT INTO `ak_items`(title,category,keywords)VALUES('专利维权案猛增两个月受理量是上半年5倍多','2','专利,维权,猛增');
INSERT INTO `ak_items`(title,category,keywords)VALUES('CRT等离子回暖液晶增长彩电市场出现新变化','3','等离子,增长,液晶');
INSERT INTO `ak_items`(title,category,keywords)VALUES('芝罘质监部门查处无证生产桶装水企业23家','4','生产,芝罘,质监');
INSERT INTO `ak_items`(title,category,keywords)VALUES('烟台实施食品召回主动召回可从轻发落','5','食品,召回,实施');
INSERT INTO `ak_items`(title,category,keywords)VALUES('基民应顺势而为理性投资坚持长期投资定期关照','1','投资,基金,长期');
INSERT INTO `ak_items`(title,category,keywords)VALUES('[温馨生活提示]西红柿一定要带皮吃','2','番茄,温馨,生活');
INSERT INTO `ak_items`(title,category,keywords)VALUES('消协发布消费警示“800”并非真伪标签','3','消协,电话,消费');
INSERT INTO `ak_items`(title,category,keywords)VALUES('[温馨生活提示]哪些坏习惯在偷走你的寿命','1','自己,生活,温馨');
INSERT INTO `ak_items`(title,category,keywords)VALUES('打流感疫苗还感冒专家：疫苗只预防流感','1','疫苗,流感,感冒');
INSERT INTO `ak_items`(title,category,keywords)VALUES('警惕假人血白蛋白、狂犬疫苗发现请立即举报','4','警惕,假人,蛋白');
INSERT INTO `ak_items`(title,category,keywords)VALUES('生活奔小康安全不能忘画册进农家宣传交通法','1','安全,交通,生活');
INSERT INTO `ak_items`(title,category,keywords)VALUES('夜半村中独自游荡翻墙破门消磨时光','5','夜半,自游,破门');
INSERT INTO `ak_items`(title,category,keywords)VALUES('芝罘区安全部门拆除存在隐患的废弃烟囱','1','芝罘,安全,部门');
INSERT INTO `ak_items`(title,category,keywords)VALUES('客车柴油用尽无法行驶烟威高速路政热心帮忙','6','客车,柴油,无法');
INSERT INTO `ak_items`(title,category,keywords)VALUES('抢“绿灯”惹祸四车连环相撞','2','绿灯,货车,惹祸');
INSERT INTO `ak_items`(title,category,keywords)VALUES('当了17年情人曾经少女步入不惑追悔莫及','3','女士,情人,当了');
INSERT INTO `ak_items`(title,category,keywords)VALUES('两韩国人钓鱼在悬崖遇险获救','41','韩国,钓鱼,悬崖');
INSERT INTO `ak_items`(title,category,keywords)VALUES('奇特的乳茄（组图）','4','奇特,组图,的乳茄');
INSERT INTO `ak_items`(title,category,keywords)VALUES('定下“硬杠杠”饼干新国标出台','1','饼干,定下,杠杠');
INSERT INTO `ak_items`(title,category,keywords)VALUES('专利维权案猛增两个月受理量是上半年5倍多','5','专利,维权,猛增');
INSERT INTO `ak_items`(title,category,keywords)VALUES('CRT等离子回暖液晶增长彩电市场出现新变化','1','等离子,增长,液晶');
INSERT INTO `ak_items`(title,category,keywords)VALUES('芝罘质监部门查处无证生产桶装水企业23家','2','生产,芝罘,质监');
INSERT INTO `ak_items`(title,category,keywords)VALUES('烟台实施食品召回主动召回可从轻发落','5','食品,召回,实施');
INSERT INTO `ak_items`(title,category,keywords)VALUES('基民应顺势而为理性投资坚持长期投资定期关照','1','投资,基金,长期');
INSERT INTO `ak_items`(title,category,keywords)VALUES('[温馨生活提示]西红柿一定要带皮吃','4','番茄,温馨,生活');
INSERT INTO `ak_items`(title,category,keywords)VALUES('消协发布消费警示“800”并非真伪标签','1','消协,电话,消费');
INSERT INTO `ak_items`(title,category,keywords)VALUES('[温馨生活提示]哪些坏习惯在偷走你的寿命','3','自己,生活,温馨');
INSERT INTO `ak_items`(title,category,keywords)VALUES('打流感疫苗还感冒专家：疫苗只预防流感','1','疫苗,流感,感冒');
INSERT INTO `ak_items`(title,category,keywords)VALUES('警惕假人血白蛋白、狂犬疫苗发现请立即举报','2','警惕,假人,蛋白');
INSERT INTO `ak_items`(title,category,keywords)VALUES('生活奔小康安全不能忘画册进农家宣传交通法','3','安全,交通,生活');
INSERT INTO `ak_items`(title,category,keywords)VALUES('夜半村中独自游荡翻墙破门消磨时光','4','夜半,自游,破门');
INSERT INTO `ak_items`(title,category,keywords)VALUES('芝罘区安全部门拆除存在隐患的废弃烟囱','5','芝罘,安全,部门');
INSERT INTO `ak_items`(title,category,keywords)VALUES('客车柴油用尽无法行驶烟威高速路政热心帮忙','6','客车,柴油,无法');
INSERT INTO `ak_items`(title,category,keywords)VALUES('抢“绿灯”惹祸四车连环相撞','1','绿灯,货车,惹祸');
INSERT INTO `ak_items`(title,category,keywords)VALUES('当了17年情人曾经少女步入不惑追悔莫及','1','女士,情人,当了');
INSERT INTO `ak_items`(title,category,keywords)VALUES('两韩国人钓鱼在悬崖遇险获救','1','韩国,钓鱼,悬崖');
INSERT INTO `ak_items`(title,category,keywords)VALUES('奇特的乳茄（组图）','1','奇特,组图,的乳茄');
INSERT INTO `ak_categories`(id,category)VALUES('2', '栏目2');
INSERT INTO `ak_categories`(id,category)VALUES('3', '栏目3');
INSERT INTO `ak_categories`(id,category)VALUES('4', '栏目4');
INSERT INTO `ak_categories`(id,category)VALUES('5', '栏目5');
INSERT INTO `ak_categories`(id,category)VALUES('6', '栏目6');