INSERT INTO `ak_items`(title,category)VALUES('aaaaaaaaaaaaaaaaaaaaa','1');
INSERT INTO `ak_items`(title,category)VALUES('bbbbbbbbbbbbbbbbbbb','2');
INSERT INTO `ak_items`(title,category)VALUES('ccccccccccccccccc','3');
INSERT INTO `ak_items`(title,category)VALUES('ddddddddddddddddddddddddd','4');
INSERT INTO `ak_items`(title,category)VALUES('eeeeeeeeeeeeeeeeee','5');
INSERT INTO `ak_items`(title,category)VALUES('ffffffffffffffffffffffffff','1');
INSERT INTO `ak_items`(title,category)VALUES('gggggggggggggggggg','2');
INSERT INTO `ak_items`(title,category)VALUES('hhhhhhhhhhhhhhhhhhhhhhh','3');
INSERT INTO `ak_items`(title,category)VALUES('iiiiiiiiiiiiiiiiiiiiii','1');
INSERT INTO `ak_items`(title,category)VALUES('jjjjjjjjjjjjjjjjjjjj','1');
INSERT INTO `ak_items`(title,category)VALUES('kkkkkkkkkkkkkkkkk','4');
INSERT INTO `ak_items`(title,category)VALUES('lllllllllllllllllllll','1');
INSERT INTO `ak_items`(title,category)VALUES('mmmmmmmmmmmmmmmmmmmmmm','5');
INSERT INTO `ak_items`(title,category)VALUES('nnnnnnnnnnnnnnnnn','1');
INSERT INTO `ak_items`(title,category)VALUES('ooooooooooooooo','6');
INSERT INTO `ak_items`(title,category)VALUES('pppppppppppppppppppppp','2');
INSERT INTO `ak_items`(title,category)VALUES('qqqqqqqqqqqqqqqqqqqqqqqqq','3');
INSERT INTO `ak_items`(title,category)VALUES('rrrrrrrrrrrrrrrrrrrrrr','41');
INSERT INTO `ak_items`(title,category)VALUES('sssssssssssssssssssssssssssss','4');
INSERT INTO `ak_items`(title,category)VALUES('aaaaaaaaaaaaaaaaaaaaa','1');
INSERT INTO `ak_items`(title,category)VALUES('bbbbbbbbbbbbbbbbbbb','5');
INSERT INTO `ak_items`(title,category)VALUES('ccccccccccccccccc','1');
INSERT INTO `ak_items`(title,category)VALUES('ddddddddddddddddddddddddd','2');
INSERT INTO `ak_items`(title,category)VALUES('eeeeeeeeeeeeeeeeee','5');
INSERT INTO `ak_items`(title,category)VALUES('ffffffffffffffffffffffffff','1');
INSERT INTO `ak_items`(title,category)VALUES('gggggggggggggggggg','4');
INSERT INTO `ak_items`(title,category)VALUES('hhhhhhhhhhhhhhhhhhhhhhh','1');
INSERT INTO `ak_items`(title,category)VALUES('iiiiiiiiiiiiiiiiiiiiii','3');
INSERT INTO `ak_items`(title,category)VALUES('jjjjjjjjjjjjjjjjjjjj','1');
INSERT INTO `ak_items`(title,category)VALUES('kkkkkkkkkkkkkkkkk','2');
INSERT INTO `ak_items`(title,category)VALUES('lllllllllllllllllllll','3');
INSERT INTO `ak_items`(title,category)VALUES('mmmmmmmmmmmmmmmmmmmmmm','4');
INSERT INTO `ak_items`(title,category)VALUES('nnnnnnnnnnnnnnnnn','5');
INSERT INTO `ak_items`(title,category)VALUES('ooooooooooooooo','6');
INSERT INTO `ak_items`(title,category)VALUES('pppppppppppppppppppppp','1');
INSERT INTO `ak_items`(title,category)VALUES('qqqqqqqqqqqqqqqqqqqqqqqqq','1');
INSERT INTO `ak_items`(title,category)VALUES('rrrrrrrrrrrrrrrrrrrrrr','1');
INSERT INTO `ak_items`(title,category)VALUES('sssssssssssssssssssssssssssss','1');
INSERT INTO `ak_categories`(id,category)VALUES('2', 'category2');
INSERT INTO `ak_categories`(id,category)VALUES('3', 'category3');
INSERT INTO `ak_categories`(id,category)VALUES('4', 'category4');
INSERT INTO `ak_categories`(id,category)VALUES('5', 'category5');
INSERT INTO `ak_categories`(id,category)VALUES('6', 'category6');